apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "niral-one.fullname" . }}
  labels:
    {{- include "niral-one.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "niral-one.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "niral-one.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: WEBUI_NAME
              value: {{ .Values.webui.name | quote }}
            - name: WEBUI_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "niral-one.fullname" . }}
                  key: WEBUI_SECRET_KEY
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "niral-one.fullname" . }}-data
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
