apiVersion: v1
kind: Secret
metadata:
  name: {{ include "niral-one.fullname" . }}
  labels:
    {{- include "niral-one.labels" . | nindent 4 }}
type: Opaque
stringData:
  WEBUI_SECRET_KEY: {{ .Values.webui.secretKey | quote }}
