apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "{{ .Values.secrets.dockerRegistry.username }}",
          "password": "{{ .Values.secrets.dockerRegistry.password }}"
        }
      }
    }
